
package vistas;

import Conexion.MySQLConection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dario
 */
public class frmAsignacion extends javax.swing.JDialog {
     private void insertarcomision(){
        try {
            PreparedStatement ps= null;
            ResultSet rs = null;
            Connection conn = MySQLConection.getConnection();
            int fila2 = jtEmpleados.getSelectedRow();
            String numEmpleado = jtEmpleados.getValueAt(fila2, 0).toString();
            String user =jtEmpleados.getValueAt(fila2, 2).toString();
            String sql="UPDATE empleados SET comision=? WHERE numEmpleado=?";
                    
                  
                      
            ps.setDouble(1, Double.parseDouble(txtcomision.getText()));
            ps.setInt(2, Integer.parseInt(user));
            ps=conn.prepareStatement(sql);
            
            rs= ps.executeQuery();
            
            /*Double comision;
            comision= (Double.valueOf("comision"));*/
            
            
            
        } catch (Exception e) {
            
        }
   

}

    private void actualizarTablaArreglo(){
          try {
              DefaultTableModel model = new DefaultTableModel();
              jtArreglos.setModel(model);
              PreparedStatement ps=null;
              ResultSet rs =null;
              Connection conn = MySQLConection.getConnection();
              String querry=("SELECT idArreglo, nombreArreglo,tiempoElaboracion, comision FROM catalogoarreglos");
              ps= conn.prepareStatement(querry);
              rs=ps.executeQuery();
              ResultSetMetaData rsm= rs.getMetaData();
              int columnas = rsm.getColumnCount();
              model.addColumn("ID");
              model.addColumn("NOMBRE");
              model.addColumn("TIEMPO ELAB.");
              model.addColumn("Comision");
              
              int [] anchos = {20,200,50,50};
              for(int x=0; x<columnas; x++){
                  jtArreglos.getColumnModel().getColumn(x).setPreferredWidth(anchos[x]);  
              }
              while(rs.next()){
                  Object[] filas = new Object[columnas];
                  for(int i=0; i<columnas; i++){
                      filas[i]=rs.getObject(i+1);
                  }
                  model.addRow(filas);
              }
              
              
          } catch (Exception e) {
              JOptionPane.showMessageDialog(null, "Error al actualizar"+e);
          }
    }
    
     private void actualizartablaEmpleado(){
        
        try {
            DefaultTableModel model =new DefaultTableModel();
            jtEmpleados.setModel(model);
            PreparedStatement ps= null;
            ResultSet rs= null;
            Connection conn = MySQLConection.getConnection();
            String sql = "SELECT numEmpleado, nombreEmpleado, user FROM empleados";
            ps = conn.prepareStatement(sql);
            rs = ps.executeQuery();
            ResultSetMetaData rsMeta = rs.getMetaData();
            int columnas = rsMeta.getColumnCount();
            model.addColumn("ID");
            model.addColumn("NOMBRE");
            model.addColumn("USUARIO");
            
            int[]anchos = {20, 200, 100};
            for(int x =0; x<columnas; x++){
                jtEmpleados.getColumnModel().getColumn(x).setPreferredWidth(anchos[x]);
            }
            while(rs.next()){
                Object[] filas = new Object[columnas];
                for(int i=0; i<columnas; i++ ){
                    filas[i]= rs.getObject(i+1);
                }
                model.addRow(filas);
                
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al actualizar"+e);
        }
    
    
    }
    public frmAsignacion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        actualizarTablaArreglo();
        actualizartablaEmpleado();
        setLocationRelativeTo(parent);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtEmpleados = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtArreglos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnAsignar = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        txtTiempo = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        txtcomision = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(122, 14, 2), 2, true));

        jLabel1.setFont(new java.awt.Font("Montserrat Black", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(122, 14, 2));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_job_50px.png"))); // NOI18N
        jLabel1.setText("Asignacion de Tareas");

        jtEmpleados.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(122, 14, 2)));
        jtEmpleados.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jtEmpleados.setForeground(new java.awt.Color(122, 14, 2));
        jtEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "User"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtEmpleadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtEmpleados);

        jtArreglos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(122, 14, 2)));
        jtArreglos.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jtArreglos.setForeground(new java.awt.Color(122, 14, 2));
        jtArreglos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Tiempo Estimado", "Comision"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtArreglos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtArreglosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtArreglos);

        jLabel2.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(122, 14, 2));
        jLabel2.setText("Empleados");

        jLabel3.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(122, 14, 2));
        jLabel3.setText("Arreglos");

        jLabel4.setFont(new java.awt.Font("Montserrat Black", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(122, 14, 2));
        jLabel4.setText("Pedido Asignado a:");

        jLabel5.setFont(new java.awt.Font("Montserrat Black", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(122, 14, 2));
        jLabel5.setText("Tiempo Estimado:");

        btnAsignar.setBackground(new java.awt.Color(255, 255, 255));
        btnAsignar.setFont(new java.awt.Font("Montserrat Black", 0, 14)); // NOI18N
        btnAsignar.setForeground(new java.awt.Color(122, 14, 2));
        btnAsignar.setText("Asignar Pedido");
        btnAsignar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(122, 14, 2)));
        btnAsignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Montserrat Black", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(122, 14, 2));
        jButton2.setText("Salir");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(122, 14, 2)));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Montserrat Black", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(122, 14, 2));
        jLabel6.setText("Comision:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(225, 225, 225))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtcomision, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAsignar, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane2))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(278, 278, 278))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(txtTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(txtcomision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addComponent(btnAsignar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarActionPerformed
        try {
            //String user1=loginSesion.user;
            String querry=("INSERT INTO pedidosempleado (estatus, tiempoEstimado, numeroEmpleado, idArreglo, user,comision) values(?,?,?,?,?,?)");
            Connection conn = MySQLConection.getConnection();
            PreparedStatement ps = conn.prepareStatement(querry);
            String estatus="asignado";
            int fila = jtArreglos.getSelectedRow();         
            String tiempoElavoracion = jtArreglos.getValueAt(fila, 2).toString();
            String idArreglo = jtArreglos.getValueAt(fila, 0).toString();
            
            int fila2 = jtEmpleados.getSelectedRow();
            String numEmpleado = jtEmpleados.getValueAt(fila2, 0).toString();
            String user =jtEmpleados.getValueAt(fila2, 2).toString();
           
            ps.setString(1, estatus);
            ps.setString(2, tiempoElavoracion);
            ps.setInt(3, Integer.parseInt(numEmpleado));
            ps.setInt(4, Integer.parseInt(idArreglo));
            ps.setString(5, user);
            ps.setDouble(6, Double.valueOf(txtcomision.getText()));
            int res= ps.executeUpdate();
            //insertarcomision();
          
            if(res>0){
                JOptionPane.showMessageDialog(null, "Trabajo asignado correctamente");
            }else{JOptionPane.showMessageDialog(null, "Error al asignar trabajo");}
            conn.close();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"error"+e);
        }
       
    }//GEN-LAST:event_btnAsignarActionPerformed

    private void jtArreglosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtArreglosMouseClicked
        int fila = jtArreglos.getSelectedRow();         
            String tiempoElavoracion = jtArreglos.getValueAt(fila, 2).toString();
            String comision = jtArreglos.getValueAt(fila, 3).toString();
            txtTiempo.setText(tiempoElavoracion);
            txtcomision.setText(comision);
         
    }//GEN-LAST:event_jtArreglosMouseClicked

    private void jtEmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtEmpleadosMouseClicked
         int fila = jtEmpleados.getSelectedRow();         
            String nombre = jtEmpleados.getValueAt(fila, 1).toString();
            txtNombre.setText(nombre);
    }//GEN-LAST:event_jtEmpleadosMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAsignacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAsignacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAsignacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAsignacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmAsignacion dialog = new frmAsignacion(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsignar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jtArreglos;
    private javax.swing.JTable jtEmpleados;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTiempo;
    private javax.swing.JTextField txtcomision;
    // End of variables declaration//GEN-END:variables
}
