/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import Conexion.MySQLConection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dario
 */
public class frmCatalogoArreglo extends javax.swing.JDialog {
     private void limpiar(){
         txtNombreArreglo.setText("");
         txtCosto.setText("");
         txtTiempo.setText("");
     };
    
      private void actualizarTabla(){
          try {
              DefaultTableModel model = new DefaultTableModel();
              jtArreglos.setModel(model);
              PreparedStatement ps=null;
              ResultSet rs =null;
              Connection conn = MySQLConection.getConnection();
              String querry=("SELECT idArreglo, nombreArreglo, costoArreglo, tiempoElaboracion, comision FROM catalogoarreglos");
              ps= conn.prepareStatement(querry);
              rs=ps.executeQuery();
              ResultSetMetaData rsm= rs.getMetaData();
              int columnas = rsm.getColumnCount();
              model.addColumn("ID");
              model.addColumn("NOMBRE");
              model.addColumn("COSTO");
              model.addColumn("TIEMPO ELAB.");
              model.addColumn("COMISIÓN");
              int [] anchos = {20,200,50,50,50};
              for(int x=0; x<columnas; x++){
                  jtArreglos.getColumnModel().getColumn(x).setPreferredWidth(anchos[x]);  
              }
              while(rs.next()){
                  Object[] filas = new Object[columnas];
                  for(int i=0; i<columnas; i++){
                      filas[i]=rs.getObject(i+1);
                  }
                  model.addRow(filas);
              }
              
              
          } catch (Exception e) {
              JOptionPane.showMessageDialog(null, "Error al actualizar"+e);
          }
       
       
       } 
        
    
    
    
    public frmCatalogoArreglo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        actualizarTabla();
     
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombreArreglo = new javax.swing.JTextField();
        txtCosto = new javax.swing.JTextField();
        txtTiempo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtArreglos = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnMod = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        btnDel1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Montserrat SemiBold", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(122, 14, 2));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_flower_bouquet_50px.png"))); // NOI18N
        jLabel1.setText("Arreglos");

        jLabel2.setFont(new java.awt.Font("Montserrat Black", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(122, 14, 2));
        jLabel2.setText("Nombre del Arreglo:");

        jLabel3.setFont(new java.awt.Font("Montserrat Black", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(122, 14, 2));
        jLabel3.setText("Costo del Arreglo:");

        jLabel4.setFont(new java.awt.Font("Montserrat Black", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(122, 14, 2));
        jLabel4.setText("Tiempo de elaboración:");

        txtNombreArreglo.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        txtNombreArreglo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(122, 14, 2), 1, true));
        txtNombreArreglo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreArregloActionPerformed(evt);
            }
        });

        txtCosto.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        txtCosto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(122, 14, 2), 1, true));
        txtCosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCostoActionPerformed(evt);
            }
        });

        txtTiempo.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        txtTiempo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(122, 14, 2), 1, true));
        txtTiempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTiempoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Montserrat Black", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(122, 14, 2));
        jLabel6.setText("$");

        jtArreglos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOMBRE", "COSTO", "TIEMPO ELAB.", "COMISIÓN"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtArreglos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtArreglosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtArreglos);

        btnAdd.setBackground(new java.awt.Color(255, 255, 255));
        btnAdd.setFont(new java.awt.Font("Montserrat Black", 1, 14)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(122, 14, 2));
        btnAdd.setText("Agregar");
        btnAdd.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(122, 14, 2), 1, true));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnMod.setBackground(new java.awt.Color(255, 255, 255));
        btnMod.setFont(new java.awt.Font("Montserrat Black", 1, 14)); // NOI18N
        btnMod.setForeground(new java.awt.Color(122, 14, 2));
        btnMod.setText("Modificar");
        btnMod.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(122, 14, 2), 1, true));
        btnMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModActionPerformed(evt);
            }
        });

        btnDel.setBackground(new java.awt.Color(255, 255, 255));
        btnDel.setFont(new java.awt.Font("Montserrat Black", 1, 14)); // NOI18N
        btnDel.setForeground(new java.awt.Color(122, 14, 2));
        btnDel.setText("Eliminar");
        btnDel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(122, 14, 2), 1, true));
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });

        btnDel1.setBackground(new java.awt.Color(255, 255, 255));
        btnDel1.setFont(new java.awt.Font("Montserrat Black", 1, 14)); // NOI18N
        btnDel1.setForeground(new java.awt.Color(122, 14, 2));
        btnDel1.setText("Salir");
        btnDel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(122, 14, 2), 1, true));
        btnDel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDel1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtTiempo, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txtCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)))
                .addGap(402, 402, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombreArreglo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(295, 295, 295))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnMod, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDel, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnDel1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombreArreglo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMod, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreArregloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreArregloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreArregloActionPerformed

    private void txtCostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCostoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCostoActionPerformed

    private void txtTiempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTiempoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTiempoActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        try {
            String querry=("INSERT INTO catalogoarreglos (nombreArreglo, costoArreglo, tiempoElaboracion, comision) values(?,?,?,?)");
            Connection conn = MySQLConection.getConnection();
            PreparedStatement ps = conn.prepareStatement(querry);
            /*--------- calculo de comision----------*/
            double comision;
            double precio= Double.parseDouble(txtCosto.getText());
            comision= precio*.05;
            
            ps.setString(1, txtNombreArreglo.getText());
            ps.setDouble(2, Double.parseDouble(txtCosto.getText()));
            ps.setString(3, txtTiempo.getText());
            ps.setDouble(4, comision);
            int res=ps.executeUpdate();
            
            if(res>0){
                JOptionPane.showMessageDialog(null, "arreglo agregado exitosamente");
               limpiar();
               actualizarTabla();
            }else {JOptionPane.showMessageDialog(null, "error al guardar arreglo");
                limpiar();
            }
            conn.close();
  
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Error de conexion al servidor"+e.getMessage());
            limpiar();
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
            PreparedStatement ps = null;
            try {
                
            int fila = jtArreglos.getSelectedRow();
            String idArreglo = jtArreglos.getValueAt(fila, 0).toString();
            Connection conn = MySQLConection.getConnection();    
            String querry=("DELETE FROM catalogoarreglos WHERE idArreglo=?");
            ps=conn.prepareStatement(querry);
            ps.setString(1, idArreglo);
            ps.execute();
            actualizarTabla();
            limpiar();
            JOptionPane.showMessageDialog(null,"elemento eliminado");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"error en eliminado"+e);
        }
    }//GEN-LAST:event_btnDelActionPerformed

    private void jtArreglosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtArreglosMouseClicked
            btnAdd.setEnabled(false);
            btnDel.setEnabled(true);
            btnMod.setEnabled(true);
            int fila = jtArreglos.getSelectedRow();
            String idArreglo = jtArreglos.getValueAt(fila, 0).toString();
            String nombreArreglo= jtArreglos.getValueAt(fila, 1).toString();
            String costoArreglo = jtArreglos.getValueAt(fila, 2).toString();
            String tiempoElavoracio = jtArreglos.getValueAt(fila, 3).toString();
            
            txtNombreArreglo.setText(nombreArreglo);
            txtCosto.setText(costoArreglo);
            txtTiempo.setText(tiempoElavoracio);
    }//GEN-LAST:event_jtArreglosMouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        btnAdd.setEnabled(true);
        btnDel.setEnabled(false);
        btnMod.setEnabled(false);
        jtArreglos.clearSelection();
        limpiar();
    }//GEN-LAST:event_jPanel1MouseClicked

    private void btnModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModActionPerformed
       
        PreparedStatement ps= null;
        
        try { 
            int fila = jtArreglos.getSelectedRow();
            String idArreglo = jtArreglos.getValueAt(fila, 0).toString();
            
            
            Connection conn= MySQLConection.getConnection();
            ps= conn.prepareStatement("UPDATE catalogoarreglos SET nombreArreglo=?, costoArreglo=?, tiempoElaboracion=? WHERE idArreglo=?");
            ps.setString(1, txtNombreArreglo.getText());
            ps.setDouble(2, Double.parseDouble(txtCosto.getText()));
            ps.setString(3, txtTiempo.getText());
            ps.setString(4, idArreglo );
            ps.execute();
            JOptionPane.showMessageDialog(null, "arreglo modificado con exito");
            actualizarTabla();
            limpiar();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnModActionPerformed

    private void btnDel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDel1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnDel1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCatalogoArreglo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCatalogoArreglo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCatalogoArreglo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCatalogoArreglo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmCatalogoArreglo dialog = new frmCatalogoArreglo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnDel1;
    private javax.swing.JButton btnMod;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jtArreglos;
    public javax.swing.JTextField txtCosto;
    public javax.swing.JTextField txtNombreArreglo;
    public javax.swing.JTextField txtTiempo;
    // End of variables declaration//GEN-END:variables
}
